<?php
/**
 * Test class for Erfurt_Rdf_Resource.
 * Generated by PHPUnit on 2009-06-08 at 10:38:28.
 */
class Erfurt_Rdf_ResourceIntegrationTest extends Erfurt_TestCase
{
    /**
     * @var    Erfurt_Rdf_Resource
     * @access protected
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->_object = new Erfurt_Rdf_Resource('http://example.org/resource1');
    }

    /**
     * @todo Implement testGetQualifiedName().
     */
    public function testGetQualifiedName()
    {
        // First we test with the standard object (no qname).
        $this->assertEquals(null, $this->_object->getQualifiedName());
        
        // Now we test with a real qname.
        $this->markTestNeedsDatabase();
        $this->authenticateDbUser();
        $model = Erfurt_App::getInstance()->getSysOntModel();
        
        $r = new Erfurt_Rdf_Resource(EF_RDF_TYPE, $model);
        $this->assertEquals('rdf:type', $r->getQualifiedName());
    }
    
    public function testGetDescription()
    {
        $this->markTestNeedsDatabase();
        $this->authenticateDbUser();
        $model = Erfurt_App::getInstance()->getSysOntModel();
        $resource = new Erfurt_Rdf_Resource('http://ns.ontowiki.net/SysOnt/Anonymous', $model);
        
        $expected = array(
            'http://ns.ontowiki.net/SysOnt/Anonymous' => array(
                'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' => array(
                    array(
                        'type' => 'uri', 
                        'value' => 'http://rdfs.org/sioc/ns#User'
                    )
                ), 
                'http://www.w3.org/2000/01/rdf-schema#label' => array(
                    array(
                        'type' => 'literal', 
                        'value' => 'Anonymous'
                    )
                ), 
                'http://www.w3.org/2000/01/rdf-schema#comment' => array(
                    array(
                        'type' => 'literal', 
                        'value' => 'This special account identifies the anonymous user.'
                    )
                ), 
                'http://ns.ontowiki.net/SysOnt/grantAccess' => array(
                    array(
                        'type' => 'uri', 
                        'value' => 'http://ns.ontowiki.net/SysOnt/RegisterNewUser'
                    )
                ), 
                'http://ns.ontowiki.net/SysOnt/grantModelEdit' => array(
                    array(
                        'type' => 'uri', 
                        'value' => 'http://ns.ontowiki.net/SysOnt/AnyModel'
                    )
                ),
                'http://ns.ontowiki.net/SysOnt/grantModelView' => array(
                    array(
                        'type' => 'uri', 
                        'value' => 'http://ns.ontowiki.net/SysOnt/AnyModel'
                    ), 
                    array(
                        'type' => 'uri', 
                        'value' => 'http://ns.ontowiki.net/SysBase/'
                    )
                ), 
                'http://ns.ontowiki.net/SysOnt/denyModelView' => array(
                    array(
                        'type' => 'uri', 
                        'value' => 'http://ns.ontowiki.net/SysOnt/'
                    )
                ), 
                'http://ns.ontowiki.net/SysOnt/denyAccess' => array(
                    array(
                        'type' => 'uri', 
                        'value' => 'http://ns.ontowiki.net/SysOnt/Login'
                    ), 
                    array(
                        'type' => 'uri', 
                        'value' => 'http://ns.ontowiki.net/SysOnt/Rollback'
                    )
                )
            )
        );
        
        $this->assertEquals($expected, $resource->getDescription());
    }
}
