<?php
/**
 * Test class for Erfurt_Rdf_Resource.
 * Generated by PHPUnit on 2009-06-08 at 10:38:28.
 */
class Erfurt_Rdf_ResourceIntegrationTest extends Erfurt_TestCase
{
    /**
     * @var    Erfurt_Rdf_Resource
     * @access protected
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->_object = new Erfurt_Rdf_Resource('http://example.org/resource1');
    }

    /**
     * @todo Implement testGetQualifiedName().
     */
    public function testGetQualifiedName()
    {
        // Issue: https://github.com/Matthimatiker/Erfurt/issues/7
        $this->markTestSkipped('TODO: Currently, this test works neither on Travis (Ubuntu) nor on Win7.');

        $this->markTestNeedsDatabase();
        $this->authenticateDbUser();

        // First we test with the standard object (no qname).
        $this->assertEquals(null, $this->_object->getQualifiedName());

        // Now we test with a real qname.
        $model = Erfurt_App::getInstance()->getSysOntModel();
        $r = new Erfurt_Rdf_Resource(EF_RDF_TYPE, $model);
        $this->assertEquals('rdf:type', $r->getQualifiedName());
    }
    
    public function testGetDescription()
    {
        $this->markTestNeedsDatabase();
        $this->authenticateDbUser();
        $model = Erfurt_App::getInstance()->getSysOntModel();
        $resource = new Erfurt_Rdf_Resource('http://ns.ontowiki.net/SysOnt/Anonymous', $model);

        $description = $resource->getDescription();
        $this->assertTrue(isset($description['http://ns.ontowiki.net/SysOnt/Anonymous']));
        $anonymousDesc = $description['http://ns.ontowiki.net/SysOnt/Anonymous'];

        $this->assertTrue(isset($anonymousDesc['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']));
        $this->assertTrue(isset($anonymousDesc['http://www.w3.org/2000/01/rdf-schema#label']));
        $this->assertTrue(isset($anonymousDesc['http://www.w3.org/2000/01/rdf-schema#comment']));
    }
}
