language: php

php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1

matrix:
    allow_failures:
        - php: 7.0
        - php: 7.1

sudo: false

before_install:
  - phpenv config-rm xdebug.ini

install:
  - travis_retry composer install --no-interaction

before_script:
  - make directories

script: vendor/bin/phpunit --testsuite "Erfurt Unit Tests"
