language: php

services:
  - mysql

php:
  - 5.3
  - 5.4
  - 5.5

install:
  - make zend
  - make directories

before_script:
  # Create a new database for testing.
  - mysql -e 'create database erfurt_TEST;'
  # Activate the Travis Integration Test configuration.
  - cp tests/config.ini.travis tests/config.ini

script:
  - make test-unit
  - make test-integration-mysql