language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'

sudo: false

addons:
  apt:
    packages:
    - raptor-utils

before_install:
  - phpenv config-rm xdebug.ini

install:
  - sudo apt-get install -y --force-yes raptor-utils

before_script:
  - make directories

script: composer unittest