language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'

sudo: false

before_install:
  - sudo apt-get update > /dev/null
  - phpenv config-rm xdebug.ini

install:
  - sudo apt-get install -y --force-yes raptor-utils
  - travis_retry composer install --no-interaction

before_script:
  - make directories

script: composer unittest