language: php

php:
  - 5.4

sudo: false

before_install:
  - phpenv config-rm xdebug.ini

install:
  - travis_retry composer install --no-interaction

before_script:
  - make directories

script: vendor/bin/phpunit --testsuite "Erfurt Unit Tests"