SELECT DISTINCT ?uri ?uri0 ?uri1
FROM <http://3ba.se/conferences/>
WHERE {
    ?instance ?uri ?o.
    ?instance a ?type
    FILTER (str(?uri) != <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
    FILTER (sameTerm(?type, <http://swrc.ontoware.org/ontology#Person>))                
    OPTIONAL { ?uri <http://www.w3.org/2000/01/rdf-schema#label> ?uri0. }
    OPTIONAL { ?uri <http://purl.org/dc/elements/1.1/title> ?uri1. }
}
LIMIT 20