<?php
require_once 'Erfurt/TestCase.php';

require_once 'Erfurt/Owl/Model.php';

/**
 * Test class for Erfurt_Owl_Model.
 * Generated by PHPUnit on 2009-06-08 at 10:41:53.
 */
class Erfurt_Owl_ModelTest extends Erfurt_TestCase
{
    /**
     * @var    Erfurt_Owl_Model
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new Erfurt_Owl_Model;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetImportedIris().
     */
    public function testGetImportedIris()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetResource().
     */
    public function testGetResource()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
