<?php
require_once 'Erfurt/TestCase.php';
require_once 'Erfurt/Owl/Model.php';

/**
 * Test class for Erfurt_Owl_Model.
 * Generated by PHPUnit on 2009-06-08 at 10:41:53.
 */
class Erfurt_Owl_ModelTest extends Erfurt_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    public function testObjectCreationWithoutBaseUriAndWithoutImports()
    {
        $model = new Erfurt_Owl_Model('http://example.org/model/');
        $this->assertTrue($model instanceof Erfurt_Owl_Model);
    }
}
?>
