<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-03 at 21:06:37.
 */
class Erfurt_PingTest extends Erfurt_TestCase
{
    /**
     * @var Erfurt_Ping
     */
    protected $ping;
    protected $adapter;
    protected $_store;
    protected $_dataDir;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->_dataDir = realpath(dirname(__FILE__)) . '/_files/data/';

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Erfurt_Ping::receive
     */
    public function testReceiveSuccess()
    {
        $this->_setupStore();

        $modelUri = 'http://example.org/';
        $source = 'http://example.org/testResource1';
        $target = 'http://example.org/testResource1target';

        $model = $this->_store->getModelOrCreate($modelUri);
        $model->addStatement($target, EF_RDF_TYPE, array('type' => 'uri', 'value' => 'http://object.org'));

        // prepare HTTP adapter
        $this->_adapter = new Zend_Http_Client_Adapter_Test();
        $this->_adapter->setResponse(
            new Zend_Http_Response(
                200,
                array('Content-type' => 'application/rdf+xml'),
                file_get_contents($this->_dataDir . 'testResource1.rdf')
            )
        );

        // prepare Ping
        $this->_ping = new Erfurt_Ping;
        $this->_ping->setHttpAdapter($this->_adapter);

        $successText = 'Pingback has been registered or updated... Keep spinning the Data Web ;-)';
        $this->assertEquals($successText, $this->_ping->receive($source, $target));
    }

    /**
     * @covers Erfurt_Ping::receive
     */
    public function testReceiveTargetNotExists()
    {
        $this->_setupStore();

        $modelUri = 'http://example.org/';
        $source = 'http://example.org/testResource1';
        $target = 'http://example.org/testResource1target';

        // prepare HTTP adapter
        $this->_adapter = new Zend_Http_Client_Adapter_Test();
        $this->_adapter->setResponse(
            new Zend_Http_Response(
                200,
                array('Content-type' => 'application/rdf+xml'),
                file_get_contents($this->_dataDir . 'testResource1.rdf')
            )
        );

        // prepare Ping
        $this->_ping = new Erfurt_Ping;
        $this->_ping->setHttpAdapter($this->_adapter);

        $failureCode = 0x0021;
        $this->assertEquals($failureCode, $this->_ping->receive($source, $target));
    }

    private function _setupStore ()
    {
        //$this->markTestNeedsDatabase();
        $this->markTestNeedsTestConfig();

        // prepare Erfurt_App
        $testConfig = $this->getTestConfig();
        $testConfig->debug = true;
        $testConfig->store->backend = 'memory';

        Erfurt_App::reset();
        Erfurt_App::getInstance(false)->start($testConfig);

        $app = Erfurt_App::getInstance();

        $this->markTestIncomplete('This test doesn\'t work because of an authentication problem in _setupStore');
        // PHP Fatal error:  Call to a member function getUri() on a non-object in Erfurt/library/Erfurt/Versioning.php on line 606
        $this->authenticateDbUser();

        // prepare Model
        $this->_store = $app->getStore();
    }
}
