<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-03 at 21:06:37.
 */
class Erfurt_PingTest extends Erfurt_TestCase
{
    /**
     * @var Erfurt_Ping
     */
    protected $ping;
    protected $adapter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

        $this->_dataDir = realpath(dirname(__FILE__)) . '/_files/data/';
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Erfurt_Ping::receive
     * @todo   Implement testReceive().
     */
    public function testReceive()
    {
        //$this->markTestNeedsDatabase();
        $this->markTestNeedsTestConfig();

        // prepare Erfurt_App
        $testConfig = $this->getTestConfig();
        $testConfig->debug = true;
        $testConfig->store->backend = 'test';

        Erfurt_App::reset();
        Erfurt_App::getInstance(false)->start($testConfig);

        $app = Erfurt_App::getInstance();
        $app->authenticate();

        $modelUri = 'http://example.org/';
        $source = 'http://example.org/testResource1';
        $target = 'http://example.org/testResource1target';

        // prepare Model
        $store = $app->getStore();
        $store->getModelOrCreate($modelUri);
        $store->addStatement($modelUri, $target, EF_RDF_TYPE, array('type' => 'uri', 'value' => 'http://object.org'));
        $all = $store->getGraphsUsingResource($target);
        $allowed = $store->getReadableGraphsUsingResource($target);

        var_dump($all);
        var_dump($allowed);

        // prepare HTTP adapter
        $this->_adapter = new Zend_Http_Client_Adapter_Test();
        $this->_adapter->setResponse(new Zend_Http_Response(
            200,
            array('Content-type' => 'application/rdf+xml'),
            file_get_contents($this->_dataDir . 'testResource1.rdf')
        ));

        // prepare Ping
        $this->_ping = new Erfurt_Ping;
        $this->_ping->setHttpAdapter($this->_adapter);

        $successText = 'Pingback has been registered or updated... Keep spinning the Data Web ;-)';
        $this->assertEquals($successText, $this->_ping->receive($source, $target));

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete( 'This test has not been implemented yet.');
    }

    protected function newCallback($className)
    {
    }
}
