<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//FR"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">
   <html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<!-- Generated by phpDocumentor on {$date}  -->
  <title>{$title}</title>
  <meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'/>
</head>

<FRAMESET cols='20%,80%'>
	<FRAMESET rows='30%,70%'>
		<FRAME src='packages.html' name='left_top' frameborder="1">
		<FRAME src='{$start}' name='left_bottom' frameborder="1">
	</FRAMESET>
	<FRAME src='{$blank}.html' name='right' frameborder="1">
	<NOFRAMES>
		<H2>Frame Alert</H2>
		<P>This document is designed to be viewed using the frames feature.
		If you see this message, you are using a non-frame-capable web client.</P>
	</NOFRAMES>
</FRAMESET>
</HTML>
