<?php
// $ANTLR 3.1.3 “ˆŽ 06, 2009 18:28:01 src/Erfurt_Sparql_Parser_Sparql10_Sparql10.g 2010-03-26 00:02:35

/**
 * Do not edit this file
 *
 * This file is part of the {@link http://aksw.org/Projects/Erfurt Erfurt} project.
 *
 * @copyright Copyright (c) 2010, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * @category Erfurt
 * @package Sparql_Parser_Sparql10
 * @author Rolland Brunec <rollxx@gmail.com>
 * @copyright Copyright (c) 2010 {@link http://aksw.org aksw}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

require_once 'Erfurt/Sparql/Query2/structural-Interfaces.php';
require_once 'Erfurt/Sparql/Query2/ElementHelper.php';
require_once 'Erfurt/Sparql/Query2/ContainerHelper.php';
require_once 'Erfurt/Sparql/Query2/Constraint.php';
require_once 'Erfurt/Sparql/Query2/IriRef.php';
require_once 'Erfurt/Sparql/Query2/OrderClause.php';
require_once 'Erfurt/Sparql/Query2/GroupGraphPattern.php';
require_once 'Erfurt/Sparql/Query2/GraphClause.php';
require_once 'Erfurt/Sparql/Query2.php';



# for convenience in actions
if (!defined('HIDDEN')) define('HIDDEN', BaseRecognizer::$HIDDEN);

class Erfurt_Sparql_Parser_Sparql10_Sparql10Parser extends AntlrParser {
    public static $tokenNames = array(
        "<invalid>", "<EOR>", "<DOWN>", "<UP>", "BASE", "PREFIX", "NOT", "SELECT", "DISTINCT", "REDUCED", "CONSTRUCT", "DESCRIBE", "ASK", "FROM", "NAMED", "WHERE", "ORDER", "GROUP", "BY", "ASC", "DESC", "LIMIT", "OFFSET", "OPTIONAL", "GRAPH", "UNION", "FILTER", "A", "AS", "STR", "LANG", "LANGMATCHES", "DATATYPE", "BOUND", "SAMETERM", "ISIRI", "ISURI", "ISBLANK", "ISLITERAL", "REGEX", "TRUE", "FALSE", "LESS", "GREATER", "OPEN_CURLY_BRACE", "CLOSE_CURLY_BRACE", "IRI_REF", "PN_PREFIX", "PNAME_NS", "PN_LOCAL", "PNAME_LN", "VARNAME", "VAR1", "VAR2", "MINUS", "LANGTAG", "INTEGER", "DOT", "DECIMAL", "DIGIT", "EXPONENT", "DOUBLE", "PLUS", "INTEGER_POSITIVE", "DECIMAL_POSITIVE", "DOUBLE_POSITIVE", "INTEGER_NEGATIVE", "DECIMAL_NEGATIVE", "DOUBLE_NEGATIVE", "ECHAR", "STRING_LITERAL1", "STRING_LITERAL2", "STRING_LITERAL_LONG1", "STRING_LITERAL_LONG2", "EOL", "WS", "PN_CHARS_BASE", "PN_CHARS_U", "PN_CHARS", "BLANK_NODE_LABEL", "REFERENCE", "AND", "OR", "COMMENT", "SEMICOLON", "ASTERISK", "COMMA", "NOT_SIGN", "DIVIDE", "EQUAL", "OPEN_BRACE", "CLOSE_BRACE", "LESS_EQUAL", "GREATER_EQUAL", "NOT_EQUAL", "OPEN_SQUARE_BRACE", "CLOSE_SQUARE_BRACE", "HAT_LABEL", "QUESTION_MARK_LABEL"
    );
    public $PREFIX=5;
    public $EXPONENT=60;
    public $CLOSE_SQUARE_BRACE=96;
    public $GRAPH=24;
    public $REGEX=39;
    public $PNAME_LN=50;
    public $CONSTRUCT=10;
    public $NOT=6;
    public $EOF=-1;
    public $VARNAME=51;
    public $ISLITERAL=38;
    public $GREATER=43;
    public $EOL=74;
    public $NOT_EQUAL=94;
    public $LESS=42;
    public $LANGMATCHES=31;
    public $DOUBLE=61;
    public $BASE=4;
    public $PN_CHARS_U=77;
    public $COMMENT=83;
    public $SELECT=7;
    public $OPEN_CURLY_BRACE=44;
    public $CLOSE_CURLY_BRACE=45;
    public $DOUBLE_POSITIVE=65;
    public $BOUND=33;
    public $DIVIDE=88;
    public $ISIRI=35;
    public $A=27;
    public $NOT_SIGN=87;
    public $ASC=19;
    public $ASK=12;
    public $BLANK_NODE_LABEL=79;
    public $SEMICOLON=84;
    public $QUESTION_MARK_LABEL=98;
    public $ISBLANK=37;
    public $GROUP=17;
    public $WS=75;
    public $NAMED=14;
    public $INTEGER_POSITIVE=63;
    public $STRING_LITERAL2=71;
    public $OR=82;
    public $FILTER=26;
    public $DESCRIBE=11;
    public $STRING_LITERAL1=70;
    public $PN_CHARS=78;
    public $DATATYPE=32;
    public $LESS_EQUAL=92;
    public $DOUBLE_NEGATIVE=68;
    public $FROM=13;
    public $FALSE=41;
    public $DISTINCT=8;
    public $LANG=30;
    public $WHERE=15;
    public $IRI_REF=46;
    public $ORDER=16;
    public $LIMIT=21;
    public $AND=81;
    public $ASTERISK=85;
    public $ISURI=36;
    public $STR=29;
    public $AS=28;
    public $SAMETERM=34;
    public $COMMA=86;
    public $OFFSET=22;
    public $DECIMAL_POSITIVE=64;
    public $EQUAL=89;
    public $PLUS=62;
    public $DIGIT=59;
    public $DOT=57;
    public $INTEGER=56;
    public $BY=18;
    public $REDUCED=9;
    public $INTEGER_NEGATIVE=66;
    public $PN_LOCAL=49;
    public $PNAME_NS=48;
    public $REFERENCE=80;
    public $CLOSE_BRACE=91;
    public $MINUS=54;
    public $TRUE=40;
    public $OPEN_SQUARE_BRACE=95;
    public $UNION=25;
    public $ECHAR=69;
    public $OPTIONAL=23;
    public $HAT_LABEL=97;
    public $STRING_LITERAL_LONG2=73;
    public $PN_CHARS_BASE=76;
    public $DECIMAL=58;
    public $VAR1=52;
    public $VAR2=53;
    public $STRING_LITERAL_LONG1=72;
    public $DECIMAL_NEGATIVE=67;
    public $PN_PREFIX=47;
    public $DESC=20;
    public $OPEN_BRACE=90;
    public $GREATER_EQUAL=93;
    public $LANGTAG=55;

    // delegates
    public $gSparql10;
    // delegators

    
    static $FOLLOW_query10_in_parse60;
    static $FOLLOW_EOF_in_parse62;

    
    

        public function __construct($input, $state = null) {
            if($state==null){
                $state = new RecognizerSharedState();
            }
            parent::__construct($input, $state);
            $this->gSparql10 = new Erfurt_Sparql_Parser_Sparql10_Sparql10_Sparql10($input, $state, $this);         
            
            
        }
        

    public function getTokenNames() { return Erfurt_Sparql_Parser_Sparql10_Sparql10Parser::$tokenNames; }
    public function getGrammarFileName() { return "src/Erfurt_Sparql_Parser_Sparql10_Sparql10.g"; }


    private $_errors = array();

    public function emitErrorMessage($msg) {
         $this->_errors []= $msg;
      }

    public function getErrors(){
    	return $this->_errors;
    }



    // $ANTLR start "parse"
    // src/Erfurt_Sparql_Parser_Sparql10_Sparql10.g:62:1: parse returns [$value] : query10 EOF ; 
    public function parse(){
        $value = null;

        $query101 = null;


        try {
            // src/Erfurt_Sparql_Parser_Sparql10_Sparql10.g:63:3: ( query10 EOF ) 
            // src/Erfurt_Sparql_Parser_Sparql10_Sparql10.g:64:3: query10 EOF 
            {
            $this->pushFollow(self::$FOLLOW_query10_in_parse60);
            $query101=$this->query10();

            $this->state->_fsp--;

            $this->match($this->input,$this->getToken('EOF'),self::$FOLLOW_EOF_in_parse62); 
              $value = ($query101!=null?$query101->value:null);

            }

        }
        catch (RecognitionException $re) {
            $this->reportError($re);
            $this->recover($this->input,$re);
        }
        catch(Exception $e) {
            throw $e;
        }
        
        return $value;
    }
    // $ANTLR end "parse"

    // Delegated rules
    public function booleanLiteral() { return $this->gSparql10->booleanLiteral(); }
    public function sourceSelector() { return $this->gSparql10->sourceSelector(); }
    public function argList() { return $this->gSparql10->argList(); }
    public function graphPatternNotTriples() { return $this->gSparql10->graphPatternNotTriples(); }
    public function triplesBlock() { return $this->gSparql10->triplesBlock(); }
    public function brackettedExpression() { return $this->gSparql10->brackettedExpression(); }
    public function graphTerm() { return $this->gSparql10->graphTerm(); }
    public function limitClause() { $this->gSparql10->limitClause(); }
    public function prologue() { $this->gSparql10->prologue(); }
    public function constructTriples() { return $this->gSparql10->constructTriples(); }
    public function object() { return $this->gSparql10->object(); }
    public function datasetClause() { $this->gSparql10->datasetClause(); }
    public function multiplicativeExpression() { return $this->gSparql10->multiplicativeExpression(); }
    public function offsetClause() { $this->gSparql10->offsetClause(); }
    public function rdfLiteral() { return $this->gSparql10->rdfLiteral(); }
    public function blankNode() { return $this->gSparql10->blankNode(); }
    public function regexExpression() { return $this->gSparql10->regexExpression(); }
    public function groupOrUnionGraphPattern() { return $this->gSparql10->groupOrUnionGraphPattern(); }
    public function propertyListNotEmpty() { return $this->gSparql10->propertyListNotEmpty(); }
    public function primaryExpression() { return $this->gSparql10->primaryExpression(); }
    public function functionCall() { return $this->gSparql10->functionCall(); }
    public function graphGraphPattern() { return $this->gSparql10->graphGraphPattern(); }
    public function string() { return $this->gSparql10->string(); }
    public function numericLiteralPositive() { return $this->gSparql10->numericLiteralPositive(); }
    public function iriRefOrFunction() { return $this->gSparql10->iriRefOrFunction(); }
    public function valueLogical() { return $this->gSparql10->valueLogical(); }
    public function selectQuery() { $this->gSparql10->selectQuery(); }
    public function variable() { return $this->gSparql10->variable(); }
    public function whereClause() { $this->gSparql10->whereClause(); }
    public function numericExpression() { return $this->gSparql10->numericExpression(); }
    public function expression() { return $this->gSparql10->expression(); }
    public function conditionalAndExpression() { return $this->gSparql10->conditionalAndExpression(); }
    public function prefixDecl() { $this->gSparql10->prefixDecl(); }
    public function conditionalOrExpression() { return $this->gSparql10->conditionalOrExpression(); }
    public function numericLiteralUnsigned() { return $this->gSparql10->numericLiteralUnsigned(); }
    public function constructQuery() { $this->gSparql10->constructQuery(); }
    public function graphNode() { return $this->gSparql10->graphNode(); }
    public function constraint() { return $this->gSparql10->constraint(); }
    public function verb() { return $this->gSparql10->verb(); }
    public function propertyList() { return $this->gSparql10->propertyList(); }
    public function collection() { return $this->gSparql10->collection(); }
    public function orderCondition() { $this->gSparql10->orderCondition(); }
    public function numericLiteral() { return $this->gSparql10->numericLiteral(); }
    public function triplesNode() { return $this->gSparql10->triplesNode(); }
    public function filter() { return $this->gSparql10->filter(); }
    public function optionalGraphPattern() { return $this->gSparql10->optionalGraphPattern(); }
    public function triplesSameSubject() { return $this->gSparql10->triplesSameSubject(); }
    public function varOrIRIref() { return $this->gSparql10->varOrIRIref(); }
    public function baseDecl() { $this->gSparql10->baseDecl(); }
    public function additiveExpression() { return $this->gSparql10->additiveExpression(); }
    public function builtInCall() { return $this->gSparql10->builtInCall(); }
    public function limitOffsetClauses() { $this->gSparql10->limitOffsetClauses(); }
    public function solutionModifier() { $this->gSparql10->solutionModifier(); }
    public function groupGraphPattern() { return $this->gSparql10->groupGraphPattern(); }
    public function askQuery() { $this->gSparql10->askQuery(); }
    public function describeQuery() { $this->gSparql10->describeQuery(); }
    public function query10() { return $this->gSparql10->query10(); }
    public function prefixedName() { return $this->gSparql10->prefixedName(); }
    public function defaultGraphClause() { return $this->gSparql10->defaultGraphClause(); }
    public function numericLiteralNegative() { return $this->gSparql10->numericLiteralNegative(); }
    public function iriRef() { return $this->gSparql10->iriRef(); }
    public function relationalExpression() { return $this->gSparql10->relationalExpression(); }
    public function varOrTerm() { return $this->gSparql10->varOrTerm(); }
    public function unaryExpression() { return $this->gSparql10->unaryExpression(); }
    public function objectList() { return $this->gSparql10->objectList(); }
    public function blankNodePropertyList() { return $this->gSparql10->blankNodePropertyList(); }
    public function orderClause() { $this->gSparql10->orderClause(); }
    public function namedGraphClause() { return $this->gSparql10->namedGraphClause(); }
    public function constructTemplate() { return $this->gSparql10->constructTemplate(); }


    
}

 



Erfurt_Sparql_Parser_Sparql10_Sparql10Parser::$FOLLOW_query10_in_parse60 = new Set(array());
Erfurt_Sparql_Parser_Sparql10_Sparql10Parser::$FOLLOW_EOF_in_parse62 = new Set(array(1));

?>